name:                fastMP
version:             0.1.0.0

dependencies:
- base
- bytestring

library:
  source-dirs:         src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
    - base16-bytestring
    - common-log
    - conduit
    - ethereum-rlp
    - format
    - leveldb-haskell
    - merkle-patricia-db
    - monad-alter
    - monad-loops
    - nibblestring
    - resourcet
    - strato-model
    - text
    - transformers

executables:
  fastMP-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - base16-bytestring
      - ethereum-rlp
      - fastMP
      - format
      - leveldb-haskell
      - merkle-patricia-db
      - nibblestring
      - resourcet
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  insertMP:
    main:                insertMP.hs
    source-dirs:         app
    dependencies:
      - ethereum-rlp
      - fastMP
      - format
      - labeled-error
      - leveldb-haskell
      - merkle-patricia-db
      - monad-alter
      - nibblestring
      - transformers
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  insertLDB:
    main:                insertLDB.hs
    source-dirs:         app
    dependencies:
      - conduit
      - fastMP
      - labeled-error
      - leveldb-haskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  makeSampleKVs:
    main:                makeSampleKVs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base16-bytestring
      - strato-model
