name:                core-api2

dependencies:
- base
- persistent-postgresql
- servant-server
- strato-conf


library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-casing
  - base64-bytestring
  - binary
  - blockapps-data
  - blockapps-datadefs
  - bytestring
  - clock
  - common-log
  - conduit
  - containers
  - deepseq
  - directory
  - esqueleto
  - ethereum-discovery
  - extra
  - filepath
  - format
  - hflags
  - http-types
  - kafka-monad
  - labeled-error
  - lens
  - monad-alter
  - mtl
  - process
  - QuickCheck
  - seqevents
  - servant-client
  - servant-multipart
  - servant-multipart-client  
#  - servant-swagger-tags
  - source-tools
  - sql-monad
  - strato-model
  - swagger2
  - template-haskell
  - text
  - transformers
  - type-lits
  - unliftio
  - unordered-containers
  - blockapps-vault-wrapper-api
  - blockapps-vault-wrapper-client
  - blockapps-identity-provider-client
  - vault-monad
  - identity-monad
  - strato-redis-blockdb
  - evm-solidity
