# Strato Prometheus Configuration
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s

# Processes to scrape
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
    - targets: ['localhost:9090']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

  - job_name: 'strato-sequencer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:8050']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

  - job_name: 'core-api'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['strato:3000']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

  - job_name: 'strato-p2p'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:10248']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

# TODO enable when /metrics is implemented in vault-proxy
#   - job_name: 'vault-proxy'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['strato:8013']
#     metric_relabel_configs:
#       - target_label: instance
#         replacement: '__NODE_HOST_MARKER__'

  - job_name: 'vm-runner'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:8009']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

  - job_name: 'slipstream'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:10777']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

  - job_name: 'strato-process-monitor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['strato:10778']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

# TODO: move to Vault's prometheus when implemented
#   - job_name: 'vault-wrapper'
#     metrics_path: '/strato/v2.3/metrics'
#     static_configs:
#       - targets: ['vault-wrapper:8000']
#     metric_relabel_configs:
#       - target_label: instance
#         replacement: '__NODE_HOST_MARKER__'

  - job_name: 'apex'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apex:3009']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'

  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx:80']
    metric_relabel_configs:
      - target_label: instance
        replacement: '__NODE_HOST_MARKER__'
