name: slipstream
version: 0.1.0.0
synopsis: Solidity datatypes
description: Solidity datatypes
homepage: https://github.com/blockapps/blockapps-haskell/slipstream
copyright: 2016 BlockApps
category: Web


ghc-options: -Wall -Werror -rtsopts

dependencies:
  - base
  - bytestring
  - containers
  - common-log
  - evm-solidity
  - hflags
  - raw-strings-qq
  - resourcet

library:
  source-dirs: src/
  dependencies: 
    - aeson
    - base16-bytestring
    - binary
    - bloc2
    - blockapps-data
    - blockapps-mpdbs
    - classy-prelude
    - conduit
    - containers
    - cross-monitoring
    - deepseq
    - extra
    - format
    - lens
    - lrucache
    - kafka-monad
    - monad-alter
    - persistent
    - postgresql-typed
    - prometheus-client
    - solid-vm-model
    - scientific
    - sql-monad
    - strato-conf
    - strato-model
    - text
    - time
    - transformers
    - unliftio
    - unliftio-core
    - vm-tools
    - ordered-containers

executables:
  slipstream:
    source-dirs: exec_src/
    main: Main.hs
    dependencies:
      - base
      - bloc2
      - blockapps-init
      - hflags
      - kafka-monad
      - persistent-postgresql
      - process-monitor
      - prometheus-client
      - postgresql-typed
      - slipstream
      - sql-monad
      - transformers
      - wai-middleware-prometheus
      - warp

tests:
  slipstream-test:
    main: Main.hs
    source-dirs: tests/
    ghc-options: -dynamic
    dependencies:
      - base
      - aeson
      - aeson-qq
      - bytestring
      - classy-prelude
      - conduit
      - containers
      - hflags
      - hspec
      - hspec-expectations-lifted
      - labeled-error
      - persistent-sqlite
      - QuickCheck
      - slipstream
      - solid-vm-model
      - strato-model
      - text
      - time
      - unliftio
      - vm-tools
      - ordered-containers
      - monad-alter
      - core-api2
      - blockapps-haskoin
      - blockapps-mpdbs
      - data-default
      - blockapps-data
