name:                vrun
version:             0.1.0.0
github:              "githubuser/vrun"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vrun#readme>

dependencies:
- base
- blockapps-data
- blockapps-datadefs
- blockapps-mpdbs
- bytestring
- common-log
- hflags
- merkle-patricia-db
- prometheus-client
- strato-model
- seqevents
- time
- transformers
- vm-runner
- vm-tools

executables:
  vrun:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
