#vault-version:<VERSION>
#strato-getting-started-min-version:4.2.1
version: "3"
volumes:
  idpconfig:
      driver: local
services:
  identity-provider:
    environment:
    - IDENTITYPROVIDER_DEBUG=${IDENTITYPROVIDER_DEBUG}
    - identityProviderPort=${identityProviderPort}
    - vaultProxyUrl=${vaultProxyUrl}
    - PROCESS_MONITORING=${PROCESS_MONITORING}
    - VAULT_PROXY_DEBUG=${VAULT_PROXY_DEBUG}
    - VAULT_URL=${VAULT_URL}
    - SENDGRID_APIKEY=${SENDGRID_APIKEY}
    - cacheSize=${cacheSize}
    build: .
    image: ${IDENTTIYPROVIDER_IMAGE:-<REPO_URL>identity-provider:<VERSION>}
    restart: unless-stopped
    volumes: 
      - ./identity-provider/certs:/identity-provider/certs:ro
      - ./identity-provider/idconf.yaml:/identity-provider/idconf.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  nginx:
    depends_on:
    - identity-provider
    environment:
    - ssl=${ssl}
    - sslCertFileType=${sslCertFileType}
    - IDENTITY_PROVIDER_HOSTNAME=${IDENTITY_PROVIDER_HOSTNAME}
    - IDENTITY_PORT_VAULT_PROXY=${IDENTITY_PORT_VAULT_PROXY}
    build: .
    image: ${IDENTITYNGINX_IMAGE:-<REPO_URL>identity-nginx:<VERSION>}
    ports:
    - ${HTTP_PORT:-8000}:80 #TAG_REMOVE_WHEN_SSL_CUSTOM_HTTPS_PORT
    - ${HTTPS_PORT:-8001}:443 #TAG_REMOVE_WHEN_NO_SSL
    volumes:
    - ./ssl:/tmp/ssl:ro
    - idpconfig:/config
    - ./identity-provider/idconf.yaml:/tmp/idconf.yaml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
