timeout: 600000
VM: SolidVM
configDirPath: <configDirPath_value>
serverHost: <serverHost_value>
dockerized: true
oracleInterval: <oracleFetchInterval_value>
saleInterval: <saleUpdateInterval_value>

silverOracle:
  name: <silver_oracle_name_value>

goldOracle:
  name: <gold_oracle_name_value>

ethOracle:
  name: <eth_oracle_name_value>

usdOracle:
  name: <usd_oracle_name_value>

assets:
  - id: 0
    name: <silver_oracle_name_value>
    addresses: <silver_asset_addresses_value>
  - id: 1
    name: <gold_oracle_name_value>
    addresses: <gold_asset_addresses_value>

nodes:
  - id: 0
    label: <node_label_value>
    url: <node_url_value>
    oauth:
      appTokenCookieName: <oauth_appTokenCookieName_value>
      appTokenCookieMaxAge: 7776000000
      openIdDiscoveryUrl: >-
        <oauth_openIdDiscoveryUrl_value>
      clientId: <oauth_clientId_value>
      clientSecret: <oauth_clientSecret_value>
      scope: <oauth_scope_value>
      serviceOAuthFlow: <oauth_serviceOAuthFlow_value>
      redirectUri: <oauth_redirectUri_value>
      logoutRedirectUri: <oauth_logoutRedirectUri_value>
      tokenField: <oauth_tokenField_value>
      tokenUsernameProperty: <oauth_tokenUsernameProperty_value>
      tokenUsernamePropertyServiceFlow: <oauth_tokenUsernamePropertyServiceFlow_value>
