name: ethereum-vm
version: 0.0.4
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum EVM
category:      Data Structures
description:
    The client described in the Ethereum Yellowpaper

dependencies:
  - base
  - base16-bytestring
  - binary
  - blockapps-data
  - blockapps-haskoin
  - blockapps-mpdbs
  - bytestring
  - clockwork
  - common-log
  - containers
  - cpu
  - cryptohash
  - deepseq
  - extra
  - format
  - ghc
  - lens
  - merkle-patricia-db
  - monad-alter
  - mtl
  - nibblestring
  - ordered-containers
  - primitive
  - secp256k1-haskell
  - strato-model
  - text
  - time
  - unboxed-ref
  - unliftio
  - vector
  - vm-tools

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.EVM
    - Blockchain.EVM.Code
    - Blockchain.EVM.Environment
    - Blockchain.EVM.MutableStack
    - Blockchain.EVM.Opcodes
    - Blockchain.EVM.VMM
    - Blockchain.EVM.VMState
  ghc-options: -Wall -O2
