paths:
  /inventory/:
    get:
      security:
        - bearerAuth: []
      tags:
        - Inventory
      summary: Retrieve inventory
      produces:
        - application/json
      responses:
        200:
          description: Array of inventorys
    post:
      security:
        - bearerAuth: []
      tags:
        - Inventory
      summary: Create a inventory
      produces:
        - application/json
      requestBody:
        description: It enable user to create inventory
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/createInventory'
      responses:
        200:
          description: Object of create inventory
  /inventory/{address}/{chainId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Inventory
      summary: Retrieve a inventory
      produces:
        - application/json
      parameters:
        - in: path
          name: address
          description: address to retrieve the inventory
          required: true
        - in: path
          name: chainId
          description: chainId corresponding to the address
          required: true
          schema:
            $ref: '#/definitions/fetchInventory'
      responses:
        200:
          description: Retrieve a inventory
  /inventory/update:
    put:
      security:
        - bearerAuth: []
      tags:
        - Inventory
      summary: Update a inventory
      produces:
        - application/json
      requestBody:
        description: It enable user to update a inventory
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/updateInventory'
      responses:
        200:
          description: Retrieve a updated inventory
  /inventory/{address}/{chainId}/audit:
    get:
      security:
        - bearerAuth: []
      tags:
        - Inventory
      summary: Audit inventory
      produces:
        - application/json
      parameters:
        - in: path
          name: address
          description: address to retrieve the inventory
          required: true
        - in: path
          name: chainId
          description: chainId corresponding to the address
          required: true
          schema:
            $ref: '#/definitions/auditInventory'
      responses:
        200:
          description: List of audit
  /inventory/transferOwnership:
    post:
      security:
        - bearerAuth: []
      tags:
        - Inventory
      summary: Transfer ownership
      produces:
        - application/json
      requestBody:
        description: It enable user to transfer ownership
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/transferOwnership'
      responses:
        200:
          description: indicates success of transfer ownership
definitions:
  fetchInventory:
    address:
      type: string
    chainId:
      type: string
  createInventory:
    type: object
    properties:
      machineArgs:
        type: object
        properties:
          productId:
            type: string
          quantity:
            type: number
          pricePerUnit:
            type: number
          batchId:
            type: string
          availableQuantity:
            type: number
          status:
            type: string
          createdAt:
            type: string
  updateInventory:
    type: object
    properties:
      address:
        type: string
      chainId:
        type: string
      updates:
        type: object
        properties:
          productId:
            type: string
          quantity:
            type: number
          pricePerUnit:
            type: number
          batchId:
            type: string
          availableQuantity:
            type: number
          status:
            type: string
          createdAt:
            type: string
  auditInventory:
    address:
      type: string
    chainId:
      type: string
  transferOwnership:
    type: object
    properties:
      address:
        type: string
      chainId:
        type: string
      newOwner:
        type: string
