name:        strato-index
author:      Jamshid
copyright:   2016 Blockapps
description: Please see README.md
version:     0.1.0.0

ghc-options: -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base

library:
  source-dirs: src/
  dependencies:
  - binary
  - blockapps-data
  - blockapps-datadefs
  - bytestring
  - common-log
  - conduit
  - containers
  - extra
  - format
  - kafka-monad
  - monad-alter
  - redis-monad
  - seqevents
  - sql-monad
  - strato-conf
  - strato-model
  - strato-redis-blockdb
  - text

executables:
  strato-api-indexer:
    main: ApiIndexerMain.hs
    source-dirs: exec_src
    dependencies:
      - blockapps-data
      - blockapps-datadefs
      - blockapps-init
      - common-log
      - containers
      - evm-solidity
      - hflags
      - monad-alter
      - process-monitor
      - redis-monad
      - seqevents
      - sql-monad
      - strato-conf
      - strato-index
      - strato-model
      - strato-redis-blockdb
    other-modules:
      - Wiring

  strato-p2p-indexer:
    main: P2PIndexerMain.hs
    source-dirs: exec_src
    dependencies:
      - blockapps-data
      - blockapps-datadefs
      - blockapps-init
      - common-log
      - containers
      - evm-solidity
      - hflags
      - monad-alter
      - process-monitor
      - redis-monad
      - seqevents
      - strato-conf
      - strato-index
      - strato-model
      - strato-redis-blockdb
    other-modules:
      - Wiring

  strato-txr-indexer:
    main: TxrIndexerMain.hs
    source-dirs: exec_src/
    dependencies:
      - blockapps-data
      - blockapps-datadefs
      - blockapps-init
      - common-log
      - containers
      - evm-solidity
      - hflags
      - monad-alter
      - process-monitor
      - redis-monad
      - seqevents
      - sql-monad
      - strato-conf
      - strato-index
      - strato-model
      - strato-redis-blockdb
    other-modules:
      - Wiring

tests:
  strato-index-test:
    source-dirs: test/
    main: Spec.hs
    ghc-options: -dynamic
    dependencies:
    - blockapps-datadefs
    - bytestring
    - hspec
    - strato-index
    - strato-model
    - text

