packages:
- api/bloc/bloc2
- api/bloc/bloc2api
- api/bloc/bloc2client
- api/core
- api/strato-api

- core/blockapps-data
- core/blockapps-datadefs
- core/blockapps-mpdbs
- core/blockstanbul
- core/ethereum-discovery
- core/ethereum-encryption
- core/fast-keccak256
- core/fastMP
- core/merkle-patricia-db
- core/miner-ethash
- core/seqevents
- core/strato-conf
- core/strato-genesis
- core/strato-init
- core/strato-model
- core/strato-networks
- core/strato-p2p
- core/strato-redis-blockdb
- core/strato-sequencer
- core/strato-statediff
- core/vm-runner/
- core/vm-tools/

- highway/api
- highway/client
- highway/server

- identity-provider/api
- identity-provider/server
- identity-provider/client

- indexer/slipstream
- indexer/strato-index

- libs/blockapps-haskoin/
- libs/bloomfilter/

- libs/clockwork
- libs/common-log
- libs/composable-monads/composable-monads-base
- libs/composable-monads/kafka-monad
- libs/composable-monads/redis-monad
- libs/composable-monads/sql-monad
- libs/composable-monads/identity-monad
- libs/composable-monads/notification-monad
- libs/composable-monads/vault-monad
- libs/ethereum-rlp
- libs/format
- libs/json-rpc-server
- libs/json-rpc-client
- libs/labeled-error
- libs/kafka/milena
- libs/kafka/milena-tools
- libs/monad-alter
- libs/nibblestring
- libs/partitioner
- libs/prometheus/blockapps-init
- libs/prometheus/cross-monitoring
- libs/secp256k1-haskell
- libs/type-lits

#removing for now, too hard to keep this up to date when making large changes elsewhere
#- simulator/strato-lite

- tools/blockapps-tools
- tools/debugger-tools
- tools/process-monitor
- tools/x509-tools

- vault/api
- vault/client
- vault/server
- vault-proxy/api
- vault-proxy/server

- VM/EVM/ethereum-vm
- VM/EVM/evm-solidity
- VM/SolidVM/debugger
- VM/SolidVM/solid-vm
- VM/SolidVM/solid-vm-compiler
- VM/SolidVM/solid-vm-fuzzer
- VM/SolidVM/solid-vm-model
- VM/SolidVM/solid-vm-parser
- VM/SolidVM/solid-vm-static-analysis
- VM/SolidVM/source-tools
- VM/vrun


extra-deps:
- bitwise-1.0.0.1
- bytestring-arbitrary-0.1.3@sha256:14db64d4fe126fbad2eb8d3601bfd80a693f3131e2db0e76891feffe44f10df8,1773
- contra-tracer-0.2.0.0
- Crypto-4.2.5.2
- Decimal-0.5.2
- dom-lt-0.2.3
- ghc-debug-client-0.5.0.0
- ghc-debug-common-0.5.0.0
- ghc-debug-convention-0.5.0.0
- global-lock-0.1@sha256:b7affe140763f53f17fd9c937dfe9b8023c7d209216fb3793933957e49a7446f,1327
- hflags-0.4.3@sha256:f6b85fc7cbd170787f49225646e62d5589e5dd75abe6f26d16287e5fff3e678e,3121
- hoogle-5.0.18.4
- lens-family-th-0.5.2.1@sha256:24338a7a9bb8c8bca0d5e713ce62df066058bad6c15e6eb609593fd7fe93b3cf,1294
- monadIO-0.11.1.0@sha256:2407c8aee3a74f3eba897f7c87f702f502394aec8cd412f3d2334cc353f54f13,964
- safe-0.3.21
- semver-range-0.2.8@sha256:44918080c220cf67b6e7c8ad16f01f3cfe1ac69d4f72e528e84d566348bb23c3,1941
- servant-options-0.1.0.0@sha256:39f50166a68006250e79370372f553ca476f14d06d93fa0c401050253aeba803,914
- wai-extra-3.1.14@sha256:1b093366842dc0057cebb4a23dbf9a29269321d70fd242c7695ce0bbd80d32fb,8056



#- git: https://github.com/blockapps/milena
#  commit: 39dad725837f8d67721f3ac0f87a047ce36b2889


flags:
  secp256k1-haskell:
    ecdh: true
    recovery: true

nix:
  enable: false
  pure: false
  # See https://docs.haskellstack.org/en/stable/nix_integration/#using-a-custom-shellnix-file
  shell-file: nix/stack-integration.nix

resolver: lts-22.4 #also duplicated in docker section below
compiler-check: newer-minor
extra-include-dirs:
- /usr/local/include
- /usr/include

extra-lib-dirs:
- /usr/local/lib
- /usr/lib

allow-newer: true
allow-different-user: true
ghc-options:
  "$locals": -Wall -Werror -fwarn-redundant-constraints


# Increase the number of ticks the simplifier is allowed to use by passing the flag -fsimpl-tick-factor=N (where N is a larger number) to GHC when building your project
# Adjust the -funfolding-case-threshold and -funfolding-case-scaling flags to break any inlining loops
# Break up large modules into smaller ones
# Refactor your code to reduce the number of data constructors, type class constraints, or case expressions
# Use the -ddump-simpl-stats flag to see detailed counts of the simplifier's work, which can help you identify the specific parts of your code that are causing the problem.


docker:
  enable: true
  image: "strato-buildbase:lts-22.4"
  set-user: true
  run-args: ["--ulimit=nofile=60000"]
