name: evm-solidity
version: 0.1.0.0
synopsis: Solidity datatypes
description: Solidity datatypes
author: Eitan Chatav
maintainer: eitan@blockapps.net
copyright: 2016 BlockApps
category: Web
build-type: Simple

ghc-options: -Wall -Werror

dependencies:
  - base
  - aeson
  - base16-bytestring
  - bimap
  - bytestring
  - containers
  - Decimal
  - monad-alter
  - ordered-containers
  - parsec
  - QuickCheck
  - scientific
  - solid-vm-model
  - strato-model
  - text
  - transformers
  - unordered-containers
  - vector

library:
  source-dirs: src/
  dependencies:
  - aeson-casing
  - binary
  - cryptonite
  - deepseq
  - extra
  - generic-random
  - hashable
  - lens
  - memory
  - mtl
  - quickcheck-instances
  - semver-range
  - swagger2


# tests:
#   blockapps-solidity-test:
#     main: Main.hs
#     source-dirs: test/
#     dependencies:
#      - aeson-qq
#      - evm-solidity
#      - generic-random
#      - hspec
#      - labeled-error
#      - quickcheck-instances
#      - raw-strings-qq
#      - servant
#      - swagger2
