name:                blockapps-identity-provider-server
version:             0.1.0.0
github:              "githubuser/blockapps-identity-provider-server"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/identity-provider#readme>

dependencies:
- base


library:
  source-dirs: src
  dependencies:
  - aeson
  - base64
  - bloc2api
  - bloc2client
  - blockapps-identity-provider-api
  - blockapps-identity-provider-client
  - blockapps-vault-wrapper-client
  - blockapps-vault-wrapper-api
  - bytestring
  - common-log
  - containers
  - evm-solidity
  - http-client
  - http-client-tls
  - http-types
  - lrucache
  - monad-alter
  - mtl
  - notification-monad
  - servant-client
  - servant-server
  - solid-vm-model
  - split
  - strato-model
  - text
  - time
  - transformers
  - unliftio
  - utf8-string
  - vault-monad

executables:
  identity-provider-server:
    main:                Main.hs
    source-dirs:         app
    other-modules: [Options]
    ghc-options:
    - -threaded
    dependencies:
    - blockapps-identity-provider-server
    - bytestring
    - common-log
    - containers
    - hflags
    - strato-model
    - warp
    - yaml

tests:
  identity-provider-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
