name: strato-genesis
version: 0.0.1
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: A tool to setup the DBs for a Strato instance
category:      Data Structures
description: A tool to setup the DBs for a Strato instance

dependencies:
  - base

library:
    source-dirs: src/
    ghc-options: -Wall -O2
    dependencies:
      - aeson-casing
      - base16-bytestring
      - binary
      - blockapps-data
      - blockapps-mpdbs
      - common-log
      - containers
      - crypto-api
      - directory
      - format
      - json-stream
      - labeled-error
      - monad-alter
      - scientific
      - split
      - strato-statediff
      - time
      - vector
      - vm-tools
      - aeson
      - bytestring
      - merkle-patricia-db
      - strato-model
      - text
      - raw-strings-qq
      - solid-vm-compiler
      - solid-vm-model
      - ethereum-rlp
      - lens
      - ordered-containers


executables:
  generate-genesis:
    source-dirs: exec_src/
    main: Main.hs
    other-modules: []
    dependencies:
      - aeson
      - blockapps-data
      - bytestring
      - hflags
      - strato-genesis
      - strato-model
      - text

  genesis-setup:
    source-dirs: exec_src/
    main: GenesisSetup.hs
    other-modules: []
    dependencies:
      - strato-genesis
      - hflags

tests:
  strato-genesis-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - aeson
      - blockapps-data
      - bytestring
      - hspec
      - json-stream
      - labeled-error
      - merkle-patricia-db
      - strato-genesis
      - strato-model
      - text
      - time
      - vector
    ghc-options: -Wall -dynamic
