name: solid-vm-model

dependencies:
  - base

default-extensions:
  - BangPatterns
  - OverloadedStrings

library:
  source-dirs: src/
  dependencies:
  - aeson ==2.1.1.0
  - aeson-casing
  - attoparsec
  - base16-bytestring
  - binary
  - bytestring
  - containers
  - cryptonite
  - data-default
  - Decimal
  - deepseq
  - ethereum-rlp
  - format
  - generic-random
  - hashable
  - labeled-error
  - lens
  - QuickCheck
  - quickcheck-instances
  - scientific
  - source-tools
  - strato-model
  - swagger2
  - text
  - utf8-string
  - vector

tests:
  storage-test:
    source-dirs: test/
    main: StorageTest.hs
    ghc-options: -dynamic
    other-modules: []
    dependencies:
      - bytestring
      - ethereum-rlp
      - hspec
      - solid-vm-model
      - strato-model
      - unliftio

benchmarks:
  storage-bench:
    source-dirs: bench/
    main: StorageBench.hs
    ghc-options: -dynamic
    other-modules: []
    dependencies:
      - binary
      - bytestring
      - cereal
      - ethereum-rlp
      - solid-vm-model
      - strato-model
      - criterion
