name: strato-lite
version: 0.0.1
build-type: Simple
author: Dustin Norwood
maintainer:    dustin@blockapps.net
synopsis: An API and server used for simulating a STRATO network
category:      Debuggers
description:
     An API and server used for simulating a STRATO network

dependencies:
  - base
  - vm-tools

executables:
  strato-lite:
    source-dirs: exec_src/
    ghc-options: -Wall -Werror 
    main: Main.hs
    dependencies:
      - aeson
      - bytestring
      - hflags
      - strato-lite
      - strato-p2p
      - vm-tools

library:
  source-dirs: src/
  exposed-modules:
    - Strato.Lite
    - Strato.Lite.Options
  ghc-options: -Wall -O2 
  dependencies:
  - aeson
  - containers
  - crypto-pubkey-types
  - extra
  - hflags
  - monad-alter
  - servant-server
  - text
  - unliftio
  - warp
  - base16-bytestring
  - blockapps-data
  - blockapps-datadefs
  - blockapps-mpdbs
  - blockapps-privacy
  - blockstanbul
  - bytestring
  - common-log
  - composable-monads-base
  - conduit
  - containers
  - data-default
  - debugger
  - ethereum-discovery
  - ethereum-encryption
  - ethereum-rlp
  - hflags
  - lens
  - merkle-patricia-db
  - monad-alter
  - monadIO
  - mtl
  - network
  - nibblestring
  - ordered-containers
  - Ranged-sets
  - seqevents
  - stm-chans
  - stm-conduit
  - strato-genesis
  - strato-index
  - strato-model
  - strato-p2p
  - strato-sequencer
  - text
  - time
  - transformers
  - unliftio
  - vm-runner
  - vm-tools

tests:
  simulator-spec:
    source-dirs: tests/
    main: Main.hs
    ghc-options: -Wall -Werror -dynamic
    dependencies:
      - QuickCheck
      - blockapps-data
      - blockapps-datadefs
      - blockapps-mpdbs
      - blockstanbul
      - bytestring
      - common-log
      - conduit
      - containers
      - ethereum-encryption
      - hflags
      - ki-unlifted
      - labeled-error
      - hspec
      - lens
      - monad-alter
      - mtl
      - raw-strings-qq
      - seqevents
      - solid-vm-model
      - stm-chans
      - strato-lite
      - strato-model
      - strato-p2p
      - strato-sequencer
      - text
      - unliftio
      - vm-tools
