name: fast-keccak256
ghc-options: -Wall -Werror

dependencies:
  - base
  - bytestring

library:
  source-dirs: src/
  c-sources: c-src/keccak-tiny.c
  cc-options: -std=c11
  include-dirs: c-src/
  other-extensions: ForeignFunctionInterface
  dependencies:
  - cryptonite
  - memory

tests:
  keccak256-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
      - fast-keccak256
      - hspec

benchmarks:
  hash-bench:
    main: HashBench.hs
    source-dirs: bench/
    dependencies:
      - fast-keccak256
      - criterion
