name:                ethereum-discovery
version:             0.1.0.0
author:              jamshid
maintainer:          jim
build-type:          Simple

ghc-options: -Wall -O2

dependencies:
  - base
  - network

library:
  source-dirs: src/
  exposed-modules:
    - Blockchain.Strato.Discovery.Data.MemPeerDB
    - Blockchain.Strato.Discovery.Data.Peer
    - Blockchain.Strato.Discovery.Data.PeerIOWiring
    - Blockchain.Strato.Discovery.ContextLite
    - Blockchain.Strato.Discovery.UDP
    - Blockchain.Strato.Discovery.UDPServer
    - Blockchain.Strato.Discovery.P2PUtil
    - Executable.EthereumDiscovery
    - Executable.EthDiscoverySetup
    - Executable.Options
  dependencies:
    - base16-bytestring
    - binary
    - blockapps-data
    - blockapps-datadefs
    - blockapps-vault-wrapper-api #Will need to be changed
    - blockapps-vault-wrapper-client
    - bytestring
    - common-log
    - containers
    - composable-monads-base
    - containers
    - cpu
    - crypto-pubkey-types
    - either
    - entropy
    - errors
    - ethereum-encryption
    - ethereum-rlp
    - exceptions
    - format
    - hedis
    - hflags
    - http-client
    - labeled-error
    - lens
    - monad-alter
    - mtl
    - network-uri
    - persistent
    - persistent-postgresql
    - prometheus-client
    - random
    - servant-client
    - split
    - strato-conf
    - strato-model
    - strato-redis-blockdb
    - text
    - time
    - unliftio
    - unliftio-core

executables:
  ethereum-discover:
    source-dirs:       exec_src/
    main:             Main.hs
    dependencies:
      - blockapps-init
      - common-log
      - ethereum-discovery
      - format
      - hflags
      - mtl
      - process-monitor
      - resourcet
      - strato-conf
      - text
      - unliftio

tests:
  ethereum-discover-test:
    source-dirs: test/
    main: Spec.hs
    ghc-options: -Wall -Werror -dynamic
    dependencies:
      - ethereum-discovery
      - ethereum-rlp
      - format
      - hspec
