paths:
  /product/:
    get:
      security:
        - bearerAuth: []
      tags:
        - Product
      summary: Retrieve product
      produces:
        - application/json
      responses:
        200:
          description: Array of products
    post:
      security:
        - bearerAuth: []
      tags:
        - Product
      summary: Create a product
      produces:
        - application/json
      requestBody:
        description: It enable user to create product
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/createProduct'
      responses:
        200:
          description: Object of create product
  /product/{address}/{chainId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Product
      summary: Retrieve a product
      produces:
        - application/json
      parameters:
        - in: path
          name: address
          description: address to retrieve the product
          required: true
        - in: path
          name: chainId
          description: chainId corresponding to the address
          required: true
          schema:
            $ref: '#/definitions/fetchProduct'
      responses:
        200:
          description: Retrieve a product
  /product/update:
    put:
      security:
        - bearerAuth: []
      tags:
        - Product
      summary: Update a product
      produces:
        - application/json
      requestBody:
        description: It enable user to update a product
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/updateProduct'
      responses:
        200:
          description: Retrieve a updated product
  /product/{address}/{chainId}/audit:
    get:
      security:
        - bearerAuth: []
      tags:
        - Product
      summary: Audit product
      produces:
        - application/json
      parameters:
        - in: path
          name: address
          description: address to retrieve the product
          required: true
        - in: path
          name: chainId
          description: chainId corresponding to the address
          required: true
          schema:
            $ref: '#/definitions/auditProduct'
      responses:
        200:
          description: List of audit
  /product/transferOwnership:
    post:
      security:
        - bearerAuth: []
      tags:
        - Product
      summary: Transfer ownership
      produces:
        - application/json
      requestBody:
        description: It enable user to transfer ownership
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/transferOwnership'
      responses:
        200:
          description: indicates success of transfer ownership
definitions:
  fetchProduct:
    address:
      type: string
    chainId:
      type: string
  createProduct:
    type: object
    properties:
      machineArgs:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
          manufacturer:
            type: string
          unitOfMeasurement:
            type: string
          uniqueProductCode:
            type: string
          leastSellableUnit:
            type: number
          imageUrl:
            type: string
          fileHash:
            type: string
          isActive:
            type: boolean
          category:
            type: string
          subCategory:
            type: string
          createdAt:
            type: string
  updateProduct:
    type: object
    properties:
      address:
        type: string
      chainId:
        type: string
      updates:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
          manufacturer:
            type: string
          unitOfMeasurement:
            type: string
          uniqueProductCode:
            type: string
          leastSellableUnit:
            type: number
          imageUrl:
            type: string
          fileHash:
            type: string
          isActive:
            type: boolean
          category:
            type: string
          subCategory:
            type: string
          createdAt:
            type: string
  auditProduct:
    address:
      type: string
    chainId:
      type: string
  transferOwnership:
    type: object
    properties:
      address:
        type: string
      chainId:
        type: string
      newOwner:
        type: string
