name:                blockapps-vault-proxy-server
version:             0.1.0.0
github:              "githubuser/vault-proxy"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

dependencies:
- base
- blockapps-vault-proxy-api
- concurrent-extra

ghc-options: -Wall -Werror -threaded

library:
  source-dirs: src
  dependencies:
    - base64
    - cache
    - clock
    - exceptions
    - http-client
    - modern-uri
    - req
    - servant
    - servant-client
    - stm
    - text


executables:
  blockapps-vault-proxy-server:
    source-dirs: app
    main: Main.hs
    other-modules: [Options]
    dependencies:
      - blockapps-vault-proxy-server
      - blockapps-init
      - bytestring
      - cache
      - hflags
      - http-client
      - http-conduit
      - http-reverse-proxy
      - http-types
      - process-monitor
      - regex-compat
      - servant-client
      - servant-client-core
      - text
      - wai
      - warp
    ghc-options: -threaded
      
tests:
  vault-proxy-spec:
    source-dirs: test/
    main: Spec.hs
    ghc-options: -dynamic
    dependencies:
      - async
      - blockapps-vault-proxy-server
      - cache
      - hspec
      - mtl
      - stm
