name: strato-p2p
build-type: Simple
author: Jamshid
maintainer:    jamshidnh@gmail.com
synopsis: a microservice that handles peer to peer connections for strato

dependencies:
  - base
  - common-log

ghc-options: -Wall -threaded


executables:
  strato-p2p:
    source-dirs: exec_src/
    main: StratoP2PMain.hs
    dependencies:
      - blockapps-init
      - ethereum-discovery
      - hflags
      - lifted-async
      - ordered-containers
      - process-monitor
      - strato-model
      - strato-p2p
      - vm-tools
      - wai-middleware-prometheus
      - warp
      
library:
  source-dirs: src
  ghc-options: -Wall -O2
  dependencies:
    - aeson
    - base16-bytestring
    - blockapps-data
    - blockapps-datadefs
    - blockapps-vault-wrapper-api
    - blockapps-vault-wrapper-client
    - blockstanbul
    - bytestring
    - composable-monads-base
    - conduit
    - conduit-extra
    - containers
    - cross-monitoring
    - crypto-pubkey-types
    - data-default
    - dlist
    - dns
    - either
    - ethereum-discovery
    - ethereum-encryption
    - ethereum-rlp
    - format
    - ghc
    - hedis
    - hflags
    - http-client
    - iproute
    - kafka-monad
    - lens
    - lifted-async
    - lifted-base
    - merkle-patricia-db
    - monad-alter
    - mtl
    - network
    - ordered-containers
    - persistent
    - prometheus-client
    - random
    - Ranged-sets
    - resourcet
    - seqevents
    - servant-client
    - servant-server
    - split
    - stm-conduit
    - strato-conf
    - strato-model
    - strato-redis-blockdb
    - text
    - these
    - time
    - unliftio-core
    - unliftio 
    - warp

#removing p2p tests for now, it is more work to keep updating this than the reward it is giving
#tests:
#  strato-p2p-client-test:
#    source-dirs: test
#    ghc-options: -Wall -Werror -dynamic
#    main: Main.hs
#    dependencies:
#      - base16-bytestring
#      - blockapps-data
#      - blockapps-datadefs
#      - blockapps-mpdbs
#      - blockapps-privacy
#      - blockstanbul
#      - bytestring
#      - composable-monads-base
#      - conduit
#      - containers
#      - crypto-pubkey-types
#      - data-default
#      - debugger
#      - ethereum-encryption
#      - ethereum-discovery
#      - ethereum-rlp
#      - extra
#      - hflags
#      - hspec
#      - hspec-expectations-lifted
#      - hourglass
#      - labeled-error
#      - lens
#      - merkle-patricia-db
#      - monad-alter
#      - mtl
#      - network
#      - nibblestring
#      - ordered-containers
#      - Ranged-sets
#      - seqevents
#      - stm-chans
#      - stm-conduit
#      - strato-index
#      - strato-model
#      - strato-p2p
#      - strato-sequencer
#      - strato-redis-blockdb
#      - text
#      - time
#      - unliftio
#      - vm-runner
#      - vm-tools
#      - x509-certs

