name:                strato-statediff
version:             0.1.0.0
author:              BlockApps
maintainer:          blockapps
build-type:          Simple

library:
  source-dirs: src/
  dependencies:
    - base
    - blockapps-data
    - blockapps-datadefs
    - blockapps-mpdbs
    - bytestring
    - common-log
    - conduit
    - containers
    - ethereum-rlp
    - format
    - kafka-monad
    - lens
    - merkle-patricia-db
    - monad-alter
    - nibblestring
    - persistent
    - persistent-postgresql
    - strato-conf
    - strato-model
    - text
    - unliftio
  default-extensions:
    - MultiParamTypeClasses
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - GADTs
    - RecordWildCards
    - FunctionalDependencies
    - DataKinds
    - ExplicitForAll
    - NamedFieldPuns
    - OverloadedStrings
    - TypeFamilies
    - ViewPatterns
  ghc-options: -Wall -Werror -fno-warn-orphans -fno-warn-unused-imports
