apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: vault-platform
  template:
    metadata:
      labels:
        app: vault-platform
    spec:
      containers:
      - image: postgres:9.6
        name: postgres
        command: ["docker-entrypoint.sh"]
        args: ["-c", "max_connections=300", "-c", "shared_buffers=512MB"]
        env:
        - name: POSTGRES_PASSWORD
          value: "api"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/
            name: vault-postgres-data
      - image: <REPO_URL>vault-nginx:<VERSION>
        name: nginx
        ports:
          - containerPort: 80
          - containerPort: 443
        env:
        - name: INITIAL_OAUTH_DISCOVERY_URL
          value: "https://keycloak.blockapps.net/auth/realms/strato-devel/.well-known/openid-configuration"
        - name: INITIAL_OAUTH_ISSUER
          value: "https://keycloak.blockapps.net/auth/realms/strato-devel"
        - name: INITIAL_OAUTH_JWT_USER_ID_CLAIM
          value: "sub"
        - name: ssl
          value: ""
        - name: sslCertFileType
          value: ""
        - name: VAULT_WRAPPER_HOST
          value: "localhost:8000"
        volumeMounts:
          - mountPath: /config
            name: vault-idpconfig-data
      - image: <REPO_URL>vault-wrapper:<VERSION>
        name: vault-wrapper
        env:
        - name: keyStoreCacheTimeout
          value: "60"
        - name: postgres_host
          value: "localhost"
        - name: postgres_password
          value: "api"
        - name: postgres_port
          value: "5432"
        - name: postgres_user
          value: "postgres"
        - name: postgres_vault_wrapper_db
          value: "oauth"
        - name: VAULTWRAPPER_DEBUG
          value: "true"
      volumes:
        - name: vault-idpconfig-data
          awsElasticBlockStore:
            volumeID: vol-0b4772e3dfa5ead6d
            fsType: ext4
        - name: vault-postgres-data
          awsElasticBlockStore:
            volumeID: vol-0c7bf0878de7863d8
            fsType: ext4
