name: x509-tools
version: 0.0.1
build-type: Simple
author: dpmesko
maintainer:   daniel@blockapps.net
synopsis: A toolkit for x509 usage in STRATO
category:      Data Structures
description:
    A toolkit for x509 usage in STRATO

dependencies:
  - base >= 4 && < 5
  - bytestring
  - strato-model


ghc-options: -Wall -Werror

executables:
  x509-generator:
    source-dirs: exec_src/
    main: X509CertGenerator.hs
    other-modules: []
    dependencies:
      - aeson
      - hourglass
      - strato-model
      - transformers

  x509-keygen:
    source-dirs: exec_src/
    main: X509Keygen.hs
    other-modules: []
    dependencies:
      - aeson
      - strato-model
    
  x509-info:
    source-dirs: exec_src/
    main: X509CertInfo.hs
    other-modules: []

  x509-saltine-decrypt:
    source-dirs: exec_src/
    main: X509SaltineDecrypt.hs
    other-modules: []
    dependencies:
      - base16-bytestring
      - blockapps-vault-wrapper-api
      - blockapps-vault-wrapper-server
      - optparse-applicative
      - saltine
