apiDebug: true
timeout: 600000
VM: SolidVM
configDirPath: ./config
deployFilename: localhost.deploy.yaml
serverHost: http://localhost
serverIP:
bootMembersFilename: boot_members.yaml
cacheNonce: true
dockerized: false
marketplaceUiUrlPrefix: '/'

nodes:
  - id: 0
    label: localhost
    url: https://marketplace.mercata-testnet2.blockapps.net/
    oauth:
      appTokenCookieName: asset_framework_session
      appTokenCookieMaxAge: 7776000000
      openIdDiscoveryUrl: >-
        https://keycloak.blockapps.net/auth/realms/mercata-testnet2/.well-known/openid-configuration
      clientId: localhost
      clientSecret: 7ea4b82a-2ca9-430d-9a6f-fa9985d97f9b
      scope: email openid
      serviceOAuthFlow:
      redirectUri: http://localhost/api/v1/authentication/callback
      logoutRedirectUri: http://localhost
      tokenField: access_token
      tokenUsernameProperty:
      tokenUsernamePropertyServiceFlow:
