name:                ethereum-jsonrpc
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
category:            Web
build-type:          Simple

executables:
  ethereum-jsonrpc:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - base
      - aeson
      - base16-bytestring
      - binary
      - blaze-builder
      - blockapps-data
      - bytestring
      - containers
      - http-client
      - http-types
      - json-rpc-server
      - kafka-monad
      - mtl
      - random
      - strato-conf
      - strato-model
      - seqevents
      - text
      - vector
      - wai
      - warp
