name:                blockapps-highway-client
version:             0.1.0.0
github:              "githubuser/client"
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/client#readme>

dependencies:
- base
- blockapps-highway-api
- bytestring
- http-types
- servant-client
- servant-multipart
- servant-multipart-client
- text

library:
  source-dirs: src
