name: blockapps-data
version: 0.0.1
build-type: Simple
author: Jamshid
maintainer: jamshidnh@gmail.com
synopsis: A Haskell version of an Ethereum client
category: Data Structures
description: The client described in the Ethereum Yellowpaper

dependencies:
  - base

ghc-options: -Wall -O2

library:
  source-dirs: src/
  default-extensions: TemplateHaskell
  dependencies:
  - QuickCheck
  - aeson
  - base-unicode-symbols
  - base16-bytestring
  - binary
  - blockapps-datadefs
  - bytestring
  - bytestring-arbitrary
  - clock
  - common-log
  - composable-monads-base
  - containers
  - data-default
  - deepseq
  - esqueleto
  - ethereum-rlp
  - filepath
  - format
  - generic-arbitrary
  - generic-random
  - json-stream
  - labeled-error
  - lens
  - merkle-patricia-db
  - monad-alter
  - monad-logger
  - network
  - persistent
  - persistent-postgresql
  - quickcheck-instances
  - regex-compat
  - resourcet
  - secp256k1-haskell # remove
  - servant-docs
  - strato-conf
  - strato-model
  - swagger2
  - text
  - time
  - transformers
  - type-lits
  - unliftio
  - unliftio-core
  - vector

tests:
  blockapps-data-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - aeson
      - aeson-diff
      - binary
      - blockapps-data
      - blockapps-datadefs
      - bytestring
      - containers
      - ethereum-rlp
      - http-api-data
      - hspec
      - labeled-error
      - persistent
      - secp256k1-haskell
      - strato-model
      - text
      - vector
      - QuickCheck
    ghc-options: -Wall -Werror -threaded -rtsopts -with-rtsopts=-N -dynamic
