name: bloc2
version: 0.1.0.0
synopsis: Bloc microservice
description: Bloc microservice
category: Web
build-type: Simple


dependencies:
  - base


library:
  source-dirs: src/
  ghc-options: -Wall -Werror -fsimpl-tick-factor=15000
  dependencies:
    - base16-bytestring
    - bloc2api
    - blockapps-data
    - blockapps-datadefs
    - blockapps-mpdbs
    - blockapps-vault-wrapper-api
    - blockapps-vault-wrapper-client
    - bytestring
    - cache
    - clock
    - common-log
    - conduit
    - containers
    - core-api2
    - cryptonite
    - deepseq
    - esqueleto
    - ethereum-rlp
    - evm-solidity
    - extra
    - format
    - hashable
    - insert-ordered-containers
    - labeled-error
    - lens
    - monad-alter
    - monad-logger
    - mtl
    - parsec
    - secp256k1-haskell
    - servant-client
    - servant-server
    - servant-swagger
    - solid-vm-compiler
    - solid-vm-model
    - solid-vm-parser
    - source-tools
    - sql-monad
    - stm-conduit
    - strato-model
    - strato-redis-blockdb
    - swagger2
    - text
    - time
    - transformers
    - type-lits
    - unliftio
    - vault-monad
    - vector

tests:
  blockapps-bloc22-server-test:
    source-dirs: test/
    main: Spec.hs
    ghc-options: -Wall -Werror
    dependencies:
      - bloc2
      - hspec
