kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-idpconfig-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
